from cpanel.models import  CustomSection
from .models import CourseTitle, CountryList
from django.utils.text import slugify

def extras(request):
    customContent = ''
    country = ''
    try:
        customContent = CustomSection.objects.get(url=request.build_absolute_uri())
    except:
        pass
    courseTitle = CourseTitle.objects.all()
    country_list = CountryList.objects.all().values('country_code')
    if 'country' not in request.session:
        request.session['country'] = ''
    else:
        country = getCountry(request.session['country'])
    full_url = request.build_absolute_uri()
    url = request.build_absolute_uri().split("/")
    url = f"{url[0]}//{url[2]}/"
    slug = request.build_absolute_uri()
    slug_count = 4
    split_length = len(str(request.build_absolute_uri()).split("/"))
    if split_length > 5:
        slug_count += 1
    if 'course' in str(request.build_absolute_uri()):
        slug = request.build_absolute_uri().split("/")[slug_count]
    return {'CustomContent': customContent, 'courseTitle': courseTitle, 'country':country,'country_list': country_list,'url':url,'slug':slug,'full_url':full_url, 'split_length':split_length}


def getCountry(code):
    if len(code) < 1:
        return ""
    c = {
        'af': 'Afghanistan',
        'ax': 'Aland',
        'al': 'Albania',
        'dz': 'Algeria',
        'ad': 'Andorra',
        'ao': 'Angola',
        'ai': 'Anguilla',
        'ag': 'Antigua and Barbuda',
        'ar': 'Argentina',
        'am': 'Armenia',
        'aw': 'Aruba',
        'au': 'Australia',
        'at': 'Austria',
        'az': 'Azerbaijan',
        'bs': 'Bahamas',
        'bh': 'Bahrain',
        'bd': 'Bangladesh',
        'bb': 'Barbados',
        'by': 'Belarus',
        'be': 'Belgium',
        'bz': 'Belize',
        'bj': 'Benin',
        'bm': 'Bermuda',
        'bt': 'Bhutan',
        'bo': 'Bolivia',
        'bq': 'Bonaire Sint Eustatius ',
        'ba': 'Bosnia and Herzegovina',
        'bw': 'Botswana',
        'br': 'Brazil',
        'vg': 'British Virgin Islands',
        'bn': 'Brunei',
        'bg': 'Bulgaria',
        'bi': 'Burundi',
        'kh': 'Cambodia',
        'cm': 'Cameroon',
        'ca': 'Canada',
        'cv': 'CapeVerde',
        'cf': 'Central African Republic',
        'td': 'Chad',
        'cl': 'Chile',
        'cn': 'China',
        'co': 'Colombia',
        'cd': 'Congo',
        'ck': 'Cook Islands',
        'cr': 'Costa Rica',
        'hr': 'Croatia',
        'cu': 'Cuba',
        'cw': 'Curacao',
        'cy': 'Cyprus',
        'cz': 'Czechia',
        'dk': 'Denmark',
        'dj': 'Dijibouti',
        'dm': 'Dominica',
        'do': 'Dominican Republic',
        'tl': 'East Timor',
        'ec': 'Ecuador',
        'eg': 'Egypt',
        'sv': 'El Salvador',
        'gq': 'Equatorial Guinea',
        'ee': 'Estonia',
        'et': 'Ethiopia',
        'fo': 'Faroe Islands',
        'fi': 'Finland',
        'fr': 'France',
        'gf': 'French Guiana',
        'pf': 'French Polynesia',
        'ga': 'Gabon',
        'gm': 'Gambia',
        'ge': 'Georgia',
        'de': 'Germany',
        'gh': 'Ghana',
        'gi': 'Gibraltar',
        'gr': 'Greece',
        'gl': 'Greenland',
        'gd': 'Grenada',
        'gp': 'Guadeloupe',
        'gu': 'Guam',
        'gt': 'Guatemala',
        'gg': 'Guernsey',
        'gn': 'Guinea',
        'gw': 'Guinea-Bissau',
        'gy': 'Guyana',
        'ht': 'Haiti',
        'hn': 'Honduras',
        'hk': 'Hong Kong',
        'hu': 'Hungary',
        'is': 'Iceland',
        'in': 'India',
        'id': 'Indonesia',
        'ir': 'Iran',
        'iq': 'Iraq',
        'ie': 'Ireland',
        'im': 'Isle of Man',
        'il': 'Israel',
        'it': 'Italy',
        'jm': 'Jamaica',
        'jp': 'Japan',
        'je': 'Jersey',
        'jo': 'Jordan',
        'kz': 'Kazakhstan',
        'ke': 'Kenya',
        'ki': 'Kiribati',
        'xk': 'Kosovo',
        'kw': 'Kuwait',
        'kg': 'Kyrgyzstan',
        'la': 'Laos',
        'lv': 'Latvia',
        'lb': 'Lebanon',
        'ls': 'Lesotho',
        'lr': 'Liberia',
        'ly': 'Libya',
        'li': 'Liechtenstein',
        'lt': 'Lithuania',
        'lu': 'Luxembourg',
        'mk': 'Macedonia',
        'mg': 'Madagascar',
        'mw': 'Malawi',
        'my': 'Malaysia',
        'mv': 'Maldives',
        'ml': 'Mali',
        'mt': 'Malta',
        'mh': 'Marshall Islands',
        'mq': 'Martinique',
        'mr': 'Mauritania',
        'mu': 'Mauritius',
        'mx': 'Mexico',
        'md': 'Moldova',
        'mc': 'Monaco',
        'mn': 'Mongolia',
        'ma': 'Morocco',
        'mz': 'Mozambique',
        'mm': 'Myanmar',
        'na': 'Namibia',
        'np': 'Nepal',
        'nl': 'Netherlands',
        'nz': 'New Zealand',
        'ni': 'Nicaragua',
        'ng': 'Nigeria',
        'nu': 'Niue',
        'nf': 'Norfolk Island',
        'kp': 'North Korea',
        'mp': 'Northern Mariana Islands',
        'no': 'Norway',
        'om': 'Oman',
        'pk': 'Pakistan',
        'pw': 'Palau',
        'pa': 'Panama',
        'py': 'Paraguay',
        'pe': 'Peru',
        'ph': 'Philippines',
        'pl': 'Poland',
        'pt': 'Portugal',
        'pr': 'Puerto Rico',
        'qa': 'Qatar',
        'cg': 'Republic of the Congo',
        're': 'Reunion',
        'ro': 'Romania',
        'ru': 'Russia',
        'rw': 'Rwanda',
        'bl': 'Saint Barthelemy',
        'sh': 'Saint Helena',
        'kn': 'Saint Kitts and Nevis',
        'lc': 'Saint Lucia',
        'vc': 'Saint Vincent and ',
        'ws': 'Samoa',
        'sm': 'San Marino',
        'sa': 'Saudi Arabia',
        'sn': 'Senegal',
        'rs': 'Serbia',
        'sc': 'Seychelles',
        'sl': 'Sierra Leone',
        'sg': 'Singapore',
        'sx': 'Sint Maarten',
        'sk': 'Slovakia',
        'si': 'Slovenia',
        'sb': 'Solomon Islands',
        'so': 'Somalia',
        'za': 'South Africa',
        'kr': 'South Korea',
        'ss': 'South Sudan',
        'es': 'Spain',
        'lk': 'Sri Lanka',
        'sd': 'Sudan',
        'se': 'Sweden',
        'ch': 'Switzerland',
        'sy': 'Syria',
        'tw': 'Taiwan',
        'tj': 'Tajikistan',
        'tz': 'Tanzania',
        'th': 'Thailand',
        'tg': 'Togo',
        'tk': 'Tokelau',
        'to': 'Tonga',
        'tt': 'Trinidad and Tobago',
        'tn': 'Tunisia',
        'tr': 'Turkey',
        'tm': 'Turkmenistan',
        'tv': 'Tuvalu',
        'vi': 'U.S. Virgin Islands',
        'ug': 'Uganda',
        'ua': 'Ukraine',
        'ae': 'United Arab Emirates',
        'gb': 'United Kingdom',
        'us': 'United States',
        'uy': 'Uruguay',
        'uz': 'Uzbekistan',
        've': 'Venezuela',
        'vn': 'Vietnam',
        'ye': 'Yemen',
        'zm': 'Zambia',
        'zw': 'Zimbabwe',
    }
    return c[code]
