# Generated by Django 2.2.2 on 2022-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('select_country', models.CharField(max_length=200)),
                ('select_cities', models.CharField(max_length=200)),
                ('meta_title', models.TextField()),
                ('meta_description', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
