# Generated by Django 2.2.2 on 2022-03-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withcountry',
            name='country',
            field=models.TextField(null=True),
        ),
    ]
